import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/src/assets/font/styleFont.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} !overflow-x-clip !max-w-[1366px] mx-auto relative`}>{children}</body>
    </html>
  );
}
